//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int IdAnswer { get; set; }
        public string NameAnswer { get; set; }
        public Nullable<int> IdQuestion { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
